In [1]:
import pandas as pd

In [2]:
fintech = pd.read_excel("http://glebvasiliev.com/fintech.xlsx", sheet_name="Coinbase")
fintech

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-04-14,381.000000,429.540009,310.000000,328.279999,328.279999,81065700
1,2021-04-15,348.899994,349.200012,317.269989,322.750000,322.750000,39777900
2,2021-04-16,327.500000,345.989990,321.029999,342.000000,342.000000,22654500
3,2021-04-19,337.260010,341.010010,326.790009,333.000000,333.000000,11405600
4,2021-04-20,333.429993,334.829987,312.019989,320.820007,320.820007,18082300
5,2021-04-21,312.519989,327.470001,302.100006,311.920013,311.920013,10103900
6,2021-04-22,305.760010,313.500000,287.200012,293.450012,293.450012,14991900
7,2021-04-23,282.750000,303.000000,282.070007,291.600006,291.600006,9853800
8,2021-04-26,304.290009,306.100006,296.899994,304.540009,304.540009,6330200
9,2021-04-27,306.700012,306.700012,299.500000,302.000000,302.000000,3902000
10,2021-04-28,301.010010,302.899994,298.049988,298.049988,298.049988,2746100
11,2021-04-29,298.450012,300.000000,292.100006,294.769989,294.769989,2845800
12,2021-04-30,293.000000,302.739990,291.000000,297.640015,297.640015,3997400
13,2021-05-03,304.000000,305.029999,293.940002,294.209991,294.209991,3333800
14,2021-05-04,292.059998,292.190002,275.609985,280.660004,280.660004,5707700
15,2021-05-05,284.950012,289.149994,269.000000,273.000000,273.000000,5074600
16,2021-05-06,271.149994,272.140015,250.509995,256.760010,256.760010,8342000
17,2021-05-07,261.149994,267.070007,258.380005,263.700012,263.700012,4243700
18,2021-05-10,266.399994,297.500000,259.369995,293.450012,293.450012,10268600
19,2021-05-11,281.049988,303.320007,276.510010,303.000000,303.000000,7456000
20,2021-05-12,299.540009,306.980011,280.790009,283.609985,283.609985,7214200
21,2021-05-13,276.459991,285.000000,252.259995,265.100006,265.100006,11226800
22,2021-05-14,280.369995,280.640015,256.350006,258.369995,258.369995,11751800
23,2021-05-17,250.000000,250.250000,238.250000,248.240005,248.240005,8828100
24,2021-05-18,238.830002,252.169998,238.500000,239.000000,239.000000,7852100
25,2021-05-19,212.929993,229.000000,208.000000,224.800003,224.800003,16766000
26,2021-05-20,236.100006,238.800003,226.259995,233.399994,233.399994,10386900
27,2021-05-21,235.970001,238.970001,223.899994,224.350006,224.350006,7554900
28,2021-05-24,227.279999,231.000000,224.039993,225.300003,225.300003,10185600
29,2021-05-25,230.000000,243.990005,228.000000,242.410004,242.410004,11827800
30,2021-05-26,247.500000,249.389999,239.369995,241.520004,241.520004,6602800
31,2021-05-27,245.210007,247.240005,240.320007,247.089996,247.089996,5083300
32,2021-05-28,243.570007,244.630005,236.539993,236.539993,236.539993,5091500
33,2021-06-01,238.509995,244.710007,238.100006,238.929993,238.929993,3962700
34,2021-06-02,242.800003,243.899994,238.710007,240.479996,240.479996,3383800
35,2021-06-03,241.389999,241.500000,233.500000,233.660004,233.660004,3091100
36,2021-06-04,229.990005,233.360001,227.500000,228.789993,228.789993,3775100
37,2021-06-07,229.919998,232.559998,226.500000,231.449997,231.449997,2658300
38,2021-06-08,227.160004,229.330002,217.399994,220.660004,220.660004,6015800
39,2021-06-09,222.800003,229.789993,217.399994,224.320007,224.320007,6865900
40,2021-06-10,226.220001,229.789993,221.470001,221.850006,221.850006,3955300
41,2021-06-11,223.500000,225.740005,221.960007,223.919998,223.919998,2383500
42,2021-06-14,231.270004,239.759995,229.759995,239.100006,239.100006,6151700
43,2021-06-15,236.229996,237.669998,230.960007,232.210007,232.210007,3007900
44,2021-06-16,231.399994,234.679993,226.279999,228.050003,228.050003,2874800
45,2021-06-17,226.880005,233.229996,226.350006,230.660004,230.660004,2589600
46,2021-06-18,226.919998,232.690002,226.500000,229.289993,229.289993,3265200
47,2021-06-21,223.139999,224.990005,218.770004,222.600006,222.600006,4687600
48,2021-06-22,216.250000,223.149994,210.770004,222.470001,222.470001,6206100
49,2021-06-23,225.539993,230.520004,224.500000,226.009995,226.009995,3394700
50,2021-06-24,228.460007,230.039993,226.669998,229.929993,229.929993,2857700
51,2021-06-25,226.970001,227.820007,223.220001,224.539993,224.539993,2507000
52,2021-06-28,227.639999,248.059998,226.130005,246.690002,246.690002,7449000
53,2021-06-29,250.199997,261.149994,250.009995,254.899994,254.899994,7867600
54,2021-06-30,248.300003,254.669998,247.000000,253.300003,253.300003,4143500
55,2021-07-01,251.089996,255.149994,240.529999,241.440002,241.440002,3611300
56,2021-07-02,242.000000,246.800003,238.880005,240.720001,240.720001,2325000

In [3]:
fintech2 = pd.read_excel("http://glebvasiliev.com/fintech.xlsx", sheet_name="PayPal")
fintech2

,Date,Open,High,Low,Close,Adj Close,Volume
0,2016-07-06,35.939999,36.169998,35.715000,35.930000,35.930000,7821300
1,2016-07-07,35.919998,36.389999,35.840000,36.320000,36.320000,7326700
2,2016-07-08,36.779999,37.459999,36.660000,37.360001,37.360001,6828600
3,2016-07-11,37.450001,38.330002,37.400002,38.150002,38.150002,10096200
4,2016-07-12,38.470001,38.910000,38.240002,38.790001,38.790001,9997200
...,...,...,...,...,...,...,...
1253,2021-06-28,290.850006,294.260010,289.779999,293.649994,293.649994,5058600
1254,2021-06-29,292.970001,295.179993,291.529999,292.760010,292.760010,4333200
1255,2021-06-30,291.529999,292.700012,289.510010,291.480011,291.480011,4236000
1256,2021-07-01,290.329987,291.899994,285.760010,289.000000,289.000000,5647400
1257,2021-07-02,290.940002,292.429993,288.920013,290.239990,290.239990,4169400

In [13]:
fintech.assign(ma10 = fintech["Adj Close"].rolling(10).mean())

fintech.set_index("Date").assign(ma2w = lambda df: df["Adj Close"].rolling("14D").mean())

fintech.assign(running_mean = fintech["Adj Close"].expanding().mean())
fintech.assign(cumulative_sum = fintech["Adj Close"].cumsum())

(
fintech
    .set_index("Date")
    .assign(diff = lambda df: df["Adj Close"].diff(),
           diff2 = lambda df: df["Adj Close"].diff(2),
           pct_change = lambda df: df["Adj Close"].pct_change(),
           prev_adj_close = lambda df: df["Adj Close"].shift(1),
           prev2_adj_close = lambda df: df["Adj Close"].shift(2),
           next_adj_close = lambda df: df["Adj Close"].shift(-1))    
)

,Open,High,Low,Close,Adj Close,Volume,diff,diff2,pct_change,prev_adj_close,prev2_adj_close,next_adj_close
Date,,,,,,,,,,,,
2021-04-14,381.000000,429.540009,310.000000,328.279999,328.279999,81065700,NaN,NaN,NaN,NaN,NaN,322.750000
2021-04-15,348.899994,349.200012,317.269989,322.750000,322.750000,39777900,-5.529999,NaN,-0.016845,328.279999,NaN,342.000000
2021-04-16,327.500000,345.989990,321.029999,342.000000,342.000000,22654500,19.250000,13.720001,0.059644,322.750000,328.279999,333.000000
2021-04-19,337.260010,341.010010,326.790009,333.000000,333.000000,11405600,-9.000000,10.250000,-0.026316,342.000000,322.750000,320.820007
2021-04-20,333.429993,334.829987,312.019989,320.820007,320.820007,18082300,-12.179993,-21.179993,-0.036577,333.000000,342.000000,311.920013
2021-04-21,312.519989,327.470001,302.100006,311.920013,311.920013,10103900,-8.899994,-21.079987,-0.027741,320.820007,333.000000,293.450012
2021-04-22,305.760010,313.500000,287.200012,293.450012,293.450012,14991900,-18.470001,-27.369995,-0.059214,311.920013,320.820007,291.600006
2021-04-23,282.750000,303.000000,282.070007,291.600006,291.600006,9853800,-1.850006,-20.320007,-0.006304,293.450012,311.920013,304.540009
2021-04-26,304.290009,306.100006,296.899994,304.540009,304.540009,6330200,12.940003,11.089997,0.044376,291.600006,293.450012,302.000000
2021-04-27,306.700012,306.700012,299.500000,302.000000,302.000000,3902000,-2.540009,10.399994,-0.008340,304.540009,291.600006,298.049988
2021-04-28,301.010010,302.899994,298.049988,298.049988,298.049988,2746100,-3.950012,-6.490021,-0.013080,302.000000,304.540009,294.769989
2021-04-29,298.450012,300.000000,292.100006,294.769989,294.769989,2845800,-3.279999,-7.230011,-0.011005,298.049988,302.000000,297.640015
2021-04-30,293.000000,302.739990,291.000000,297.640015,297.640015,3997400,2.870026,-0.409973,0.009736,294.769989,298.049988,294.209991
2021-05-03,304.000000,305.029999,293.940002,294.209991,294.209991,3333800,-3.430024,-0.559998,-0.011524,297.640015,294.769989,280.660004
2021-05-04,292.059998,292.190002,275.609985,280.660004,280.660004,5707700,-13.549987,-16.980011,-0.046055,294.209991,297.640015,273.000000
2021-05-05,284.950012,289.149994,269.000000,273.000000,273.000000,5074600,-7.660004,-21.209991,-0.027293,280.660004,294.209991,256.760010
2021-05-06,271.149994,272.140015,250.509995,256.760010,256.760010,8342000,-16.239990,-23.899994,-0.059487,273.000000,280.660004,263.700012
2021-05-07,261.149994,267.070007,258.380005,263.700012,263.700012,4243700,6.940002,-9.299988,0.027029,256.760010,273.000000,293.450012
2021-05-10,266.399994,297.500000,259.369995,293.450012,293.450012,10268600,29.750000,36.690002,0.112818,263.700012,256.760010,303.000000
2021-05-11,281.049988,303.320007,276.510010,303.000000,303.000000,7456000,9.549988,39.299988,0.032544,293.450012,263.700012,283.609985
2021-05-12,299.540009,306.980011,280.790009,283.609985,283.609985,7214200,-19.390015,-9.840027,-0.063993,303.000000,293.450012,265.100006
2021-05-13,276.459991,285.000000,252.259995,265.100006,265.100006,11226800,-18.509979,-37.899994,-0.065266,283.609985,303.000000,258.369995
2021-05-14,280.369995,280.640015,256.350006,258.369995,258.369995,11751800,-6.730011,-25.239990,-0.025387,265.100006,283.609985,248.240005
2021-05-17,250.000000,250.250000,238.250000,248.240005,248.240005,8828100,-10.129990,-16.860001,-0.039207,258.369995,265.100006,239.000000
2021-05-18,238.830002,252.169998,238.500000,239.000000,239.000000,7852100,-9.240005,-19.369995,-0.037222,248.240005,258.369995,224.800003
2021-05-19,212.929993,229.000000,208.000000,224.800003,224.800003,16766000,-14.199997,-23.440002,-0.059414,239.000000,248.240005,233.399994
2021-05-20,236.100006,238.800003,226.259995,233.399994,233.399994,10386900,8.599991,-5.600006,0.038256,224.800003,239.000000,224.350006
2021-05-21,235.970001,238.970001,223.899994,224.350006,224.350006,7554900,-9.049988,-0.449997,-0.038775,233.399994,224.800003,225.300003
2021-05-24,227.279999,231.000000,224.039993,225.300003,225.300003,10185600,0.949997,-8.099991,0.004234,224.350006,233.399994,242.410004
2021-05-25,230.000000,243.990005,228.000000,242.410004,242.410004,11827800,17.110001,18.059998,0.075943,225.300003,224.350006,241.520004
2021-05-26,247.500000,249.389999,239.369995,241.520004,241.520004,6602800,-0.890000,16.220001,-0.003671,242.410004,225.300003,247.089996
2021-05-27,245.210007,247.240005,240.320007,247.089996,247.089996,5083300,5.569992,4.679992,0.023062,241.520004,242.410004,236.539993
2021-05-28,243.570007,244.630005,236.539993,236.539993,236.539993,5091500,-10.550003,-4.980011,-0.042697,247.089996,241.520004,238.929993
2021-06-01,238.509995,244.710007,238.100006,238.929993,238.929993,3962700,2.390000,-8.160003,0.010104,236.539993,247.089996,240.479996
2021-06-02,242.800003,243.899994,238.710007,240.479996,240.479996,3383800,1.550003,3.940003,0.006487,238.929993,236.539993,233.660004
2021-06-03,241.389999,241.500000,233.500000,233.660004,233.660004,3091100,-6.819992,-5.269989,-0.028360,240.479996,238.929993,228.789993
2021-06-04,229.990005,233.360001,227.500000,228.789993,228.789993,3775100,-4.870011,-11.690003,-0.020842,233.660004,240.479996,231.449997
2021-06-07,229.919998,232.559998,226.500000,231.449997,231.449997,2658300,2.660004,-2.210007,0.011626,228.789993,233.660004,220.660004
2021-06-08,227.160004,229.330002,217.399994,220.660004,220.660004,6015800,-10.789993,-8.129989,-0.046619,231.449997,228.789993,224.320007
2021-06-09,222.800003,229.789993,217.399994,224.320007,224.320007,6865900,3.660003,-7.129990,0.016587,220.660004,231.449997,221.850006
2021-06-10,226.220001,229.789993,221.470001,221.850006,221.850006,3955300,-2.470001,1.190002,-0.011011,224.320007,220.660004,223.919998
2021-06-11,223.500000,225.740005,221.960007,223.919998,223.919998,2383500,2.069992,-0.400009,0.009331,221.850006,224.320007,239.100006
2021-06-14,231.270004,239.759995,229.759995,239.100006,239.100006,6151700,15.180008,17.250000,0.067792,223.919998,221.850006,232.210007
2021-06-15,236.229996,237.669998,230.960007,232.210007,232.210007,3007900,-6.889999,8.290009,-0.028816,239.100006,223.919998,228.050003
2021-06-16,231.399994,234.679993,226.279999,228.050003,228.050003,2874800,-4.160004,-11.050003,-0.017915,232.210007,239.100006,230.660004
2021-06-17,226.880005,233.229996,226.350006,230.660004,230.660004,2589600,2.610001,-1.550003,0.011445,228.050003,232.210007,229.289993
2021-06-18,226.919998,232.690002,226.500000,229.289993,229.289993,3265200,-1.370011,1.239990,-0.005940,230.660004,228.050003,222.600006
2021-06-21,223.139999,224.990005,218.770004,222.600006,222.600006,4687600,-6.689987,-8.059998,-0.029177,229.289993,230.660004,222.470001
2021-06-22,216.250000,223.149994,210.770004,222.470001,222.470001,6206100,-0.130005,-6.819992,-0.000584,222.600006,229.289993,226.009995
2021-06-23,225.539993,230.520004,224.500000,226.009995,226.009995,3394700,3.539994,3.409989,0.015912,222.470001,222.600006,229.929993
2021-06-24,228.460007,230.039993,226.669998,229.929993,229.929993,2857700,3.919998,7.459992,0.017344,226.009995,222.470001,224.539993
2021-06-25,226.970001,227.820007,223.220001,224.539993,224.539993,2507000,-5.390000,-1.470002,-0.023442,229.929993,226.009995,246.690002
2021-06-28,227.639999,248.059998,226.130005,246.690002,246.690002,7449000,22.150009,16.760009,0.098646,224.539993,229.929993,254.899994
2021-06-29,250.199997,261.149994,250.009995,254.899994,254.899994,7867600,8.209992,30.360001,0.033281,246.690002,224.539993,253.300003
2021-06-30,248.300003,254.669998,247.000000,253.300003,253.300003,4143500,-1.599991,6.610001,-0.006277,254.899994,246.690002,241.440002
2021-07-01,251.089996,255.149994,240.529999,241.440002,241.440002,3611300,-11.860001,-13.459992,-0.046822,253.300003,254.899994,240.720001
2021-07-02,242.000000,246.800003,238.880005,240.720001,240.720001,2325000,-0.720001,-12.580002,-0.002982,241.440002,253.300003,NaN

In [20]:
pd.merge_ordered(fintech, fintech2, on="Date")
pd.merge_ordered(fintech, fintech2, on="Date", fill_method="ffill")
#.ffill()

pd.merge_asof(fintech, fintech2, on="Date")
pd.merge_asof(fintech2, fintech, on="Date")
pd.merge_asof(fintech2, fintech, on="Date", direction="forward")

,Date,Open_x,High_x,Low_x,Close_x,Adj Close_x,Volume_x,Open_y,High_y,Low_y,Close_y,Adj Close_y,Volume_y
0,2016-07-06,35.939999,36.169998,35.715000,35.930000,35.930000,7821300,381.000000,429.540009,310.000000,328.279999,328.279999,81065700
1,2016-07-07,35.919998,36.389999,35.840000,36.320000,36.320000,7326700,381.000000,429.540009,310.000000,328.279999,328.279999,81065700
2,2016-07-08,36.779999,37.459999,36.660000,37.360001,37.360001,6828600,381.000000,429.540009,310.000000,328.279999,328.279999,81065700
3,2016-07-11,37.450001,38.330002,37.400002,38.150002,38.150002,10096200,381.000000,429.540009,310.000000,328.279999,328.279999,81065700
4,2016-07-12,38.470001,38.910000,38.240002,38.790001,38.790001,9997200,381.000000,429.540009,310.000000,328.279999,328.279999,81065700
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253,2021-06-28,290.850006,294.260010,289.779999,293.649994,293.649994,5058600,227.639999,248.059998,226.130005,246.690002,246.690002,7449000
1254,2021-06-29,292.970001,295.179993,291.529999,292.760010,292.760010,4333200,250.199997,261.149994,250.009995,254.899994,254.899994,7867600
1255,2021-06-30,291.529999,292.700012,289.510010,291.480011,291.480011,4236000,248.300003,254.669998,247.000000,253.300003,253.300003,4143500
1256,2021-07-01,290.329987,291.899994,285.760010,289.000000,289.000000,5647400,251.089996,255.149994,240.529999,241.440002,241.440002,3611300
1257,2021-07-02,290.940002,292.429993,288.920013,290.239990,290.239990,4169400,242.000000,246.800003,238.880005,240.720001,240.720001,2325000

## Strings

In [29]:
import math
from datetime import date, timedelta

In [25]:
for x in range(1, 6):
    print(f"{x:1d}    {x*x:2d}            {math.sqrt(x):.2f}")

1     1            1.00
2     4            1.41
3     9            1.73
4    16            2.00
5    25            2.24

In [37]:
name = "my_name"
print(f"My name is {name}")

#if True:
#    something

True if 5 < 6 else False
print(f"Today is {'Wednesday' if date.today().weekday() == 2 else '!Wednesday'}")
print(f"Today is {date.today() + timedelta(1) if date.today().weekday() == 2 else date.today():%d.%m.%Y}")

print((
    f"First calculation:       {25**35}\n"
    f"Second calculation: {1 + 2}"
    
))

print((
    f"""First calculation:       {25**35}
Second calculation: {1 + 2}"""
    
))

#^ bitwise XOR

My name is my_name
Today is Wednesday
Today is 16.11.2023
First calculation:       8470329472543003390683225006796419620513916015625
Second calculation: 3
First calculation:       8470329472543003390683225006796419620513916015625
Second calculation: 3